apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aqeelsaeed/myimages:inventory-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/inventaryDatabase"
        - name: NODE_ENV
          value: "production"
        - name: ORIGIN_URI
          value: "*"
        - name: ACCESS_TOKEN_SECRET
          value: "hfdguybv_hjkads6283gsaHJF-agdfv6"
        - name: ACCESS_TOKEN_EXPIRY
          value: "1h"
        - name: REFRESH_TOKEN_SECRET
          value: "HJAFDF67lpqbzm084-sdn-8361gKJFKN03-HZMQ"
        - name: REFRESH_TOKEN_EXPIRY
          value: "10d"
        - name: MY_Gmail
          value: "aqeelsaeed138@gmail.com"
        - name: GMAIL_PASS
          value: "zkyhfyvyqwiaotzl"
        - name: COMPANY_NAME
          value: "Inventory-System"
        - name: DB_NAME
          value: "inventaryDatabase"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # REMOVED livenessProbe and readinessProbe
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer